dovecot_config_version = 2.4.0
dovecot_storage_version = 2.4

## The listener is added under the service auth section ##
service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  } ##end listener
} ## end service auth

auth_mechanisms = plain login

passdb passwd-file {
  passwd_file_path = /etc/dovecot/users
  default_password_scheme = crypt
}

userdb passwd-file {
  passwd_file_path = /etc/dovecot/users
}
